// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2016.robot2016.subsystems;

import org.usfirst.frc2016.robot2016.RobotMap;
import org.usfirst.frc2016.robot2016.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.CANTalon.FeedbackDevice;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class shooter extends Subsystem {

	private double localAngle = 0;
	private final double countPerDegree = 1;
//	private final double countPerDegree = (7*1188)/360;
	private boolean needsCalibrate;
	private final double AbsoluteTolerance = 0;
	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Compressor compressor = RobotMap.shooterCompressor;
    private final DoubleSolenoid shootSolenoid = RobotMap.shootershootSolenoid;
    private final CANTalon lift = RobotMap.shooterLift;
    private final SpeedController vacuumTalon = RobotMap.shooterVacuumTalon;
    private final DigitalInput shooterLowerLimit = RobotMap.shootershooterLowerLimit;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

public shooter() {
	needsCalibrate = true;

	lift.setProfile(0);
	lift.setFeedbackDevice(FeedbackDevice.QuadEncoder);
	lift.reverseSensor(false);
	lift.reverseOutput(true);
	lift.setAllowableClosedLoopErr(0);
	// Keep off until we are calibrated.
	// Hard limits should protect everything.
	lift.enableForwardSoftLimit(false);
	lift.enableReverseSoftLimit(false);
	lift.clearStickyFaults();
	lift.ClearIaccum();
	//lift.setVoltageRampRate(0);
	//lift.setCloseLoopRampRate(.00);
	//lift.configMaxOutputVoltage(12);
	// Needed for calibrate
	lift.changeControlMode(TalonControlMode.PercentVbus);	
}

public void startCalibrate() {
	lift.changeControlMode(TalonControlMode.PercentVbus);	
	needsCalibrate = true;
}
// Put methods for controlling this subsystem
    // here. Call these from Commands.
public void doCalibrate() {
	// Zero out the encoder by running the trucks backwards
	// until they reach the optical sensor on the back of the elevator
//	if (lift.isRevLimitSwitchClosed()) {
	if (!shooterLowerLimit.get()) {
		lift.set(0); // Turn off output
		localAngle = 0;
//		lift.disable();
		lift.changeControlMode(TalonControlMode.Position);
		// reset the encoder
		lift.setPosition(0);
		lift.set(0);
		lift.reverseSensor(false);
		lift.reverseOutput(true);
		lift.enable();
		needsCalibrate = false;
	} else {
		needsCalibrate = true;
		lift.set(.7); // Run back at 85% power
	}
}

    public boolean isShooterAtZero() {
    	return (!shooterLowerLimit.get());
    }
    
    public void startCompressor() {
        	compressor.start();
    }
    public void shoot() {
    	shootSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    
    public void retract() {
    	shootSolenoid.set(DoubleSolenoid.Value.kReverse);
    }

    public void off() {
    	shootSolenoid.set(DoubleSolenoid.Value.kOff);
    }
    
    public void vacuumOn() {
    	vacuumTalon.set(1);
    }

    public void vacuumOff() {
    	vacuumTalon.set(0);
    }

	public void goTo(double angle) {
		localAngle = angle;
		lift.set(angle * countPerDegree);
		//lift.enableControl();
	}

	public void incrementAngle() {
		localAngle++;
		goTo(localAngle);
	}	
	public void decremntAngle() {
		localAngle--;
		goTo(localAngle);
	}

	public boolean isPositioned() {
	
		int position;
		position = lift.getClosedLoopError();
		return (AbsoluteTolerance >= Math.abs(position));
	}
	
	public int getPositionError() {
		return lift.getClosedLoopError();
	}

	public int getPosition() {
		return (int) lift.getPosition();
	}
	
	public boolean isCalibrated(){
		return !needsCalibrate;
	}
    
	public void periodic() {
		SmartDashboard.putNumber("ShootLift Desired Pos", lift.getSetpoint());
		SmartDashboard.putNumber("Shaft Position", getPosition());
		SmartDashboard.putNumber("Position Error", getPositionError());
//		SmartDashboard.putBoolean("limit sensor", shooterLowerLimit.get());
	}
    
    public void initDefaultCommand() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

