// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2016.robot2016.subsystems;

import org.usfirst.frc2016.robot2016.RobotMap;
import org.usfirst.frc2016.robot2016.commands.*;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.networktables.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.tables.ITable;


/**
 *
 */
public class vision extends Subsystem {
	private ITable contourTable = NetworkTable.getTable("GRIP/myContoursReport");
	private double[] defaultValue = new double[0];  // value to return when tables are empty
	private double[] centerXs;
	private double[] centerYs;
	private double[] heights;
	private double[] widths;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    private void loadContours() {
    	centerXs = contourTable.getNumberArray("centerX", defaultValue);
    	centerYs = contourTable.getNumberArray("centerY", defaultValue);
    	heights = contourTable.getNumberArray("height", defaultValue);
    	widths = contourTable.getNumberArray("width", defaultValue);
    }
    
    private void displayContours() {
    	// check that we have at least 1 value
    	if (centerXs.length >0) {
    		SmartDashboard.putNumber("Center X 1", centerXs[0]);
    		SmartDashboard.putNumber("Center Y 1", centerYs[0]);
    		SmartDashboard.putNumber("Height 1", heights[0]);
    		SmartDashboard.putNumber("Width 1", widths[0]);
    	}
    	else {
    		SmartDashboard.putNumber("Center X 1", 0);
    		SmartDashboard.putNumber("Center Y 1", 0);
    		SmartDashboard.putNumber("Height 1", 0);
    		SmartDashboard.putNumber("Width 1", 0);
    	}

    	if (centerXs.length > 1) {
    		SmartDashboard.putNumber("Center 2", centerXs[1]);
    		SmartDashboard.putNumber("Center 2", centerYs[1]);
    		SmartDashboard.putNumber("Height 2", heights[1]);
    		SmartDashboard.putNumber("Width 2", widths[1]);
    	}
    	else {
    		SmartDashboard.putNumber("Center X 2", 0);
    		SmartDashboard.putNumber("Center Y 2", 0);
    		SmartDashboard.putNumber("Height 2", 0);
    		SmartDashboard.putNumber("Width 2", 0);
    	}

    	if (centerXs.length > 2) {
    		SmartDashboard.putNumber("Center X 3", centerXs[2]);
    		SmartDashboard.putNumber("Center Y 3", centerYs[2]);
    		SmartDashboard.putNumber("Height 3", heights[2]);
    		SmartDashboard.putNumber("Width 3", widths[2]);
    	}
    	else {
    		SmartDashboard.putNumber("Center X 3", 0);
    		SmartDashboard.putNumber("Center Y 3", 0);
    		SmartDashboard.putNumber("Height 3", 0);
    		SmartDashboard.putNumber("Width 3", 0);
    	}
    	if (centerXs.length > 2) {
    		SmartDashboard.putNumber("Center X 4", centerXs[3]);
    		SmartDashboard.putNumber("Center Y 4", centerYs[3]);
    		SmartDashboard.putNumber("Height 4", heights[3]);
    		SmartDashboard.putNumber("Width 4", widths[3]);
    	}
    	else {
    		SmartDashboard.putNumber("Center X 4", 0);
    		SmartDashboard.putNumber("Center Y 4", 0);
    		SmartDashboard.putNumber("Height 4", 0);
    		SmartDashboard.putNumber("Width 4", 0);
    	}
    }
}

